apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7a0q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-7a0q@sha256:b3fe3667657cc9e733ed7cc58b42c47745af190a956a3001b74c01c79bbaf1fe
        name: my-nodejs
        resources: {}
status: {}
