apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7a0q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7a0q
    app.kubernetes.io/part-of: tkrw-pr712-0075-0042-app
  name: devfile-sample-7a0q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7a0q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7a0q
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-7a0q@sha256:b3fe3667657cc9e733ed7cc58b42c47745af190a956a3001b74c01c79bbaf1fe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
